_comment_1    = "Variable file for building a CentOS 7.9 image with standard partitions"
_comment_2    = "To build run `packer build -var-file=ntnx-centos-7.9-basic.yml ntnx-centos.json`"
_comment_3    = "To build with Nutanix best practices run `packer build -var-file=ntnx.json ubuntu.json`"
iso_url       = "http://centos-distro.cavecreek.net/7.9.2009/isos/x86_64/CentOS-7-x86_64-Minimal-2009.iso"
iso_checksum  = "file:http://centos-distro.cavecreek.net/7.9.2009/isos/x86_64/sha256sum.txt"
ks_file       = "centos-7.9-ahv-x86_64.cfg"
vm_name       = "centos-7.9-ahv-x86_64"
os            = "centos"
os_ver        = "7.9"
