# This is a basic workflow to help you get started with Actions

name: build-ntnx-images

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
    #branches: [ main ]

  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '30 1 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup:
    runs-on: [ self-hosted, packer ]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true

  packer-init:
    needs: setup
    runs-on: [ self-hosted, packer ]
    strategy:
      max-parallel: 1
      matrix:
        include:
          - os_type: "linux"
            os: "centos"
            os_ver: "79"
            os_partitioning: "basic"
          - os_type: "linux"
            os: "centos"
            os_ver: "79"
            os_partitioning: "lvm"
    steps:
      - name: packer init ntnx-${{ matrix.os }}-${{ matrix.os_ver }}-${{ matrix.os_partitioning }}-x86_64.pkr.hcl
        working-directory: ${{ matrix.os }}/
        run: /usr/bin/packer init ntnx-${{ matrix.os }}-${{ matrix.os_ver }}-${{ matrix.os_partitioning }}-x86_64.pkr.hcl
      - name: packer validate ntnx-${{ matrix.os }}-${{ matrix.os_ver }}-${{ matrix.os_partitioning }}-x86_64.pkr.hcl
        working-directory: ${{ matrix.os }}/
        run: /usr/bin/packer validate ntnx-${{ matrix.os }}-${{ matrix.os_ver }}-${{ matrix.os_partitioning }}-x86_64.pkr.hcl

  packer-build:
    needs: packer-init
    runs-on: [ self-hosted, packer ]
    strategy:
      max-parallel: 1
      matrix:
        include:
          - os_type: "linux"
            os: "centos"
            os_ver: "79"
            os_partitioning: "basic"
          - os_type: "linux"
            os: "centos"
            os_ver: "79"
            os_partitioning: "lvm"
    steps:
      - name: packer build ntnx-${{ matrix.os }}-${{ matrix.os_ver }}-${{ matrix.os_partitioning }}-x86_64.pkr.hcl
        working-directory: ${{ matrix.os }}/
        run: /usr/bin/packer build ntnx-${{ matrix.os }}-${{ matrix.os_ver }}-${{ matrix.os_partitioning }}-x86_64.pkr.hcl
