# This is a basic workflow to help you get started with Actions

name: build-ntnx-images

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
    #branches: [ main ]

  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '30 1 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup:
    runs-on: [ self-hosted, packer ]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true

  packer-init:
    needs: setup
    runs-on: [ self-hosted, packer ]
    strategy:
      max-parallel: 1
      matrix:
        include:
          - os_type: "linux"
            os: "centos"
            os_ver: "7.9"
            os_partitioning: "basic"
          - os_type: "linux"
            os: "centos"
            os_ver: "7.9"
            os_partitioning: "lvm"
    steps:
      - name: packer init ntnx-${{ matrix.os }}-${{ matrix.os_ver }}-${{ matrix.os_partitioning }}-x86_64.pkr.hcl
        working-directory: ${{ matrix.os }}/
        run: /usr/bin/packer init ntnx-${{ matrix.os }}-${{ matrix.os_ver }}-${{ matrix.os_partitioning }}-x86_64.pkr.hcl
      - name: packer validate ntnx-${{ matrix.os }}-${{ matrix.os_ver }}-${{ matrix.os_partitioning }}-x86_64.pkr.hcl
        working-directory: ${{ matrix.os }}/
        run: /usr/bin/packer validate ntnx-${{ matrix.os }}-${{ matrix.os_ver }}-${{ matrix.os_partitioning }}-x86_64.pkr.hcl

  packer-build:
    needs: packer-init
    runs-on: [ self-hosted, packer ]
    strategy:
      max-parallel: 1
      matrix:
        include:
          - os_type: "linux"
            os: "centos"
            os_ver: "7.9"
            os_partitioning: "basic"
          - os_type: "linux"
            os: "centos"
            os_ver: "7.9"
            os_partitioning: "lvm"
    steps:
      - name: packer build ntnx-${{ matrix.os }}-${{ matrix.os_ver }}-${{ matrix.os_partitioning }}-x86_64.pkr.hcl
        working-directory: ${{ matrix.os }}/
        run: /usr/bin/packer build ntnx-${{ matrix.os }}-${{ matrix.os_ver }}-${{ matrix.os_partitioning }}-x86_64.pkr.hcl

  upload-qcow2-to-artifactory:
    runs-on: [ self-hosted, packer ]
    needs: packer-build
      matrix:
        include:
          - os_type: "linux"
            os: "centos"
            os_ver: "7.9"
            os_partitioning: "basic"
          - os_type: "linux"
            os: "centos"
            os_ver: "7.9"
            os_partitioning: "lvm"
    steps:
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_SECRET_1 }}
      - name: Ping Artifactory Serrver
        run: jf rt ping
      - name: Upload disk image
        run: jf rt u packer-nutanix-images/packer-nutanix-images/${{ matrix.os }}/output/ntnx-${{ matrix.os }}-${{ matrix.os_ver }}-${{ matrix.os_partitioning }}-x86_64.qcow2 ntnx-images --project ntnx --flat --target-props "os_type=${{ matrix.os_type }};os=${{ matrix.os }};os_ver=${{ matrix.os_ver }};os_arch=x86_64"
